// Code generated by ent, DO NOT EDIT.

package ent

import (
	"affluo/ent/banner"
	"affluo/ent/bannercreative"
	"affluo/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BannerCreativeUpdate is the builder for updating BannerCreative entities.
type BannerCreativeUpdate struct {
	config
	hooks    []Hook
	mutation *BannerCreativeMutation
}

// Where appends a list predicates to the BannerCreativeUpdate builder.
func (bcu *BannerCreativeUpdate) Where(ps ...predicate.BannerCreative) *BannerCreativeUpdate {
	bcu.mutation.Where(ps...)
	return bcu
}

// SetName sets the "name" field.
func (bcu *BannerCreativeUpdate) SetName(s string) *BannerCreativeUpdate {
	bcu.mutation.SetName(s)
	return bcu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (bcu *BannerCreativeUpdate) SetNillableName(s *string) *BannerCreativeUpdate {
	if s != nil {
		bcu.SetName(*s)
	}
	return bcu
}

// ClearName clears the value of the "name" field.
func (bcu *BannerCreativeUpdate) ClearName() *BannerCreativeUpdate {
	bcu.mutation.ClearName()
	return bcu
}

// SetImageURL sets the "image_url" field.
func (bcu *BannerCreativeUpdate) SetImageURL(s string) *BannerCreativeUpdate {
	bcu.mutation.SetImageURL(s)
	return bcu
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (bcu *BannerCreativeUpdate) SetNillableImageURL(s *string) *BannerCreativeUpdate {
	if s != nil {
		bcu.SetImageURL(*s)
	}
	return bcu
}

// ClearImageURL clears the value of the "image_url" field.
func (bcu *BannerCreativeUpdate) ClearImageURL() *BannerCreativeUpdate {
	bcu.mutation.ClearImageURL()
	return bcu
}

// SetSize sets the "size" field.
func (bcu *BannerCreativeUpdate) SetSize(s string) *BannerCreativeUpdate {
	bcu.mutation.SetSize(s)
	return bcu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (bcu *BannerCreativeUpdate) SetNillableSize(s *string) *BannerCreativeUpdate {
	if s != nil {
		bcu.SetSize(*s)
	}
	return bcu
}

// ClearSize clears the value of the "size" field.
func (bcu *BannerCreativeUpdate) ClearSize() *BannerCreativeUpdate {
	bcu.mutation.ClearSize()
	return bcu
}

// SetEnabled sets the "enabled" field.
func (bcu *BannerCreativeUpdate) SetEnabled(b bool) *BannerCreativeUpdate {
	bcu.mutation.SetEnabled(b)
	return bcu
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (bcu *BannerCreativeUpdate) SetNillableEnabled(b *bool) *BannerCreativeUpdate {
	if b != nil {
		bcu.SetEnabled(*b)
	}
	return bcu
}

// SetUpdatedAt sets the "updated_at" field.
func (bcu *BannerCreativeUpdate) SetUpdatedAt(t time.Time) *BannerCreativeUpdate {
	bcu.mutation.SetUpdatedAt(t)
	return bcu
}

// SetBannerID sets the "banner" edge to the Banner entity by ID.
func (bcu *BannerCreativeUpdate) SetBannerID(id int64) *BannerCreativeUpdate {
	bcu.mutation.SetBannerID(id)
	return bcu
}

// SetNillableBannerID sets the "banner" edge to the Banner entity by ID if the given value is not nil.
func (bcu *BannerCreativeUpdate) SetNillableBannerID(id *int64) *BannerCreativeUpdate {
	if id != nil {
		bcu = bcu.SetBannerID(*id)
	}
	return bcu
}

// SetBanner sets the "banner" edge to the Banner entity.
func (bcu *BannerCreativeUpdate) SetBanner(b *Banner) *BannerCreativeUpdate {
	return bcu.SetBannerID(b.ID)
}

// Mutation returns the BannerCreativeMutation object of the builder.
func (bcu *BannerCreativeUpdate) Mutation() *BannerCreativeMutation {
	return bcu.mutation
}

// ClearBanner clears the "banner" edge to the Banner entity.
func (bcu *BannerCreativeUpdate) ClearBanner() *BannerCreativeUpdate {
	bcu.mutation.ClearBanner()
	return bcu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bcu *BannerCreativeUpdate) Save(ctx context.Context) (int, error) {
	bcu.defaults()
	return withHooks(ctx, bcu.sqlSave, bcu.mutation, bcu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bcu *BannerCreativeUpdate) SaveX(ctx context.Context) int {
	affected, err := bcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bcu *BannerCreativeUpdate) Exec(ctx context.Context) error {
	_, err := bcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcu *BannerCreativeUpdate) ExecX(ctx context.Context) {
	if err := bcu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bcu *BannerCreativeUpdate) defaults() {
	if _, ok := bcu.mutation.UpdatedAt(); !ok {
		v := bannercreative.UpdateDefaultUpdatedAt()
		bcu.mutation.SetUpdatedAt(v)
	}
}

func (bcu *BannerCreativeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bannercreative.Table, bannercreative.Columns, sqlgraph.NewFieldSpec(bannercreative.FieldID, field.TypeInt64))
	if ps := bcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bcu.mutation.Name(); ok {
		_spec.SetField(bannercreative.FieldName, field.TypeString, value)
	}
	if bcu.mutation.NameCleared() {
		_spec.ClearField(bannercreative.FieldName, field.TypeString)
	}
	if value, ok := bcu.mutation.ImageURL(); ok {
		_spec.SetField(bannercreative.FieldImageURL, field.TypeString, value)
	}
	if bcu.mutation.ImageURLCleared() {
		_spec.ClearField(bannercreative.FieldImageURL, field.TypeString)
	}
	if value, ok := bcu.mutation.Size(); ok {
		_spec.SetField(bannercreative.FieldSize, field.TypeString, value)
	}
	if bcu.mutation.SizeCleared() {
		_spec.ClearField(bannercreative.FieldSize, field.TypeString)
	}
	if value, ok := bcu.mutation.Enabled(); ok {
		_spec.SetField(bannercreative.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := bcu.mutation.UpdatedAt(); ok {
		_spec.SetField(bannercreative.FieldUpdatedAt, field.TypeTime, value)
	}
	if bcu.mutation.BannerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bannercreative.BannerTable,
			Columns: []string{bannercreative.BannerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(banner.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bcu.mutation.BannerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bannercreative.BannerTable,
			Columns: []string{bannercreative.BannerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(banner.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bannercreative.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bcu.mutation.done = true
	return n, nil
}

// BannerCreativeUpdateOne is the builder for updating a single BannerCreative entity.
type BannerCreativeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BannerCreativeMutation
}

// SetName sets the "name" field.
func (bcuo *BannerCreativeUpdateOne) SetName(s string) *BannerCreativeUpdateOne {
	bcuo.mutation.SetName(s)
	return bcuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (bcuo *BannerCreativeUpdateOne) SetNillableName(s *string) *BannerCreativeUpdateOne {
	if s != nil {
		bcuo.SetName(*s)
	}
	return bcuo
}

// ClearName clears the value of the "name" field.
func (bcuo *BannerCreativeUpdateOne) ClearName() *BannerCreativeUpdateOne {
	bcuo.mutation.ClearName()
	return bcuo
}

// SetImageURL sets the "image_url" field.
func (bcuo *BannerCreativeUpdateOne) SetImageURL(s string) *BannerCreativeUpdateOne {
	bcuo.mutation.SetImageURL(s)
	return bcuo
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (bcuo *BannerCreativeUpdateOne) SetNillableImageURL(s *string) *BannerCreativeUpdateOne {
	if s != nil {
		bcuo.SetImageURL(*s)
	}
	return bcuo
}

// ClearImageURL clears the value of the "image_url" field.
func (bcuo *BannerCreativeUpdateOne) ClearImageURL() *BannerCreativeUpdateOne {
	bcuo.mutation.ClearImageURL()
	return bcuo
}

// SetSize sets the "size" field.
func (bcuo *BannerCreativeUpdateOne) SetSize(s string) *BannerCreativeUpdateOne {
	bcuo.mutation.SetSize(s)
	return bcuo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (bcuo *BannerCreativeUpdateOne) SetNillableSize(s *string) *BannerCreativeUpdateOne {
	if s != nil {
		bcuo.SetSize(*s)
	}
	return bcuo
}

// ClearSize clears the value of the "size" field.
func (bcuo *BannerCreativeUpdateOne) ClearSize() *BannerCreativeUpdateOne {
	bcuo.mutation.ClearSize()
	return bcuo
}

// SetEnabled sets the "enabled" field.
func (bcuo *BannerCreativeUpdateOne) SetEnabled(b bool) *BannerCreativeUpdateOne {
	bcuo.mutation.SetEnabled(b)
	return bcuo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (bcuo *BannerCreativeUpdateOne) SetNillableEnabled(b *bool) *BannerCreativeUpdateOne {
	if b != nil {
		bcuo.SetEnabled(*b)
	}
	return bcuo
}

// SetUpdatedAt sets the "updated_at" field.
func (bcuo *BannerCreativeUpdateOne) SetUpdatedAt(t time.Time) *BannerCreativeUpdateOne {
	bcuo.mutation.SetUpdatedAt(t)
	return bcuo
}

// SetBannerID sets the "banner" edge to the Banner entity by ID.
func (bcuo *BannerCreativeUpdateOne) SetBannerID(id int64) *BannerCreativeUpdateOne {
	bcuo.mutation.SetBannerID(id)
	return bcuo
}

// SetNillableBannerID sets the "banner" edge to the Banner entity by ID if the given value is not nil.
func (bcuo *BannerCreativeUpdateOne) SetNillableBannerID(id *int64) *BannerCreativeUpdateOne {
	if id != nil {
		bcuo = bcuo.SetBannerID(*id)
	}
	return bcuo
}

// SetBanner sets the "banner" edge to the Banner entity.
func (bcuo *BannerCreativeUpdateOne) SetBanner(b *Banner) *BannerCreativeUpdateOne {
	return bcuo.SetBannerID(b.ID)
}

// Mutation returns the BannerCreativeMutation object of the builder.
func (bcuo *BannerCreativeUpdateOne) Mutation() *BannerCreativeMutation {
	return bcuo.mutation
}

// ClearBanner clears the "banner" edge to the Banner entity.
func (bcuo *BannerCreativeUpdateOne) ClearBanner() *BannerCreativeUpdateOne {
	bcuo.mutation.ClearBanner()
	return bcuo
}

// Where appends a list predicates to the BannerCreativeUpdate builder.
func (bcuo *BannerCreativeUpdateOne) Where(ps ...predicate.BannerCreative) *BannerCreativeUpdateOne {
	bcuo.mutation.Where(ps...)
	return bcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (bcuo *BannerCreativeUpdateOne) Select(field string, fields ...string) *BannerCreativeUpdateOne {
	bcuo.fields = append([]string{field}, fields...)
	return bcuo
}

// Save executes the query and returns the updated BannerCreative entity.
func (bcuo *BannerCreativeUpdateOne) Save(ctx context.Context) (*BannerCreative, error) {
	bcuo.defaults()
	return withHooks(ctx, bcuo.sqlSave, bcuo.mutation, bcuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bcuo *BannerCreativeUpdateOne) SaveX(ctx context.Context) *BannerCreative {
	node, err := bcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bcuo *BannerCreativeUpdateOne) Exec(ctx context.Context) error {
	_, err := bcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcuo *BannerCreativeUpdateOne) ExecX(ctx context.Context) {
	if err := bcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bcuo *BannerCreativeUpdateOne) defaults() {
	if _, ok := bcuo.mutation.UpdatedAt(); !ok {
		v := bannercreative.UpdateDefaultUpdatedAt()
		bcuo.mutation.SetUpdatedAt(v)
	}
}

func (bcuo *BannerCreativeUpdateOne) sqlSave(ctx context.Context) (_node *BannerCreative, err error) {
	_spec := sqlgraph.NewUpdateSpec(bannercreative.Table, bannercreative.Columns, sqlgraph.NewFieldSpec(bannercreative.FieldID, field.TypeInt64))
	id, ok := bcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BannerCreative.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := bcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bannercreative.FieldID)
		for _, f := range fields {
			if !bannercreative.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bannercreative.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := bcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bcuo.mutation.Name(); ok {
		_spec.SetField(bannercreative.FieldName, field.TypeString, value)
	}
	if bcuo.mutation.NameCleared() {
		_spec.ClearField(bannercreative.FieldName, field.TypeString)
	}
	if value, ok := bcuo.mutation.ImageURL(); ok {
		_spec.SetField(bannercreative.FieldImageURL, field.TypeString, value)
	}
	if bcuo.mutation.ImageURLCleared() {
		_spec.ClearField(bannercreative.FieldImageURL, field.TypeString)
	}
	if value, ok := bcuo.mutation.Size(); ok {
		_spec.SetField(bannercreative.FieldSize, field.TypeString, value)
	}
	if bcuo.mutation.SizeCleared() {
		_spec.ClearField(bannercreative.FieldSize, field.TypeString)
	}
	if value, ok := bcuo.mutation.Enabled(); ok {
		_spec.SetField(bannercreative.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := bcuo.mutation.UpdatedAt(); ok {
		_spec.SetField(bannercreative.FieldUpdatedAt, field.TypeTime, value)
	}
	if bcuo.mutation.BannerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bannercreative.BannerTable,
			Columns: []string{bannercreative.BannerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(banner.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bcuo.mutation.BannerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bannercreative.BannerTable,
			Columns: []string{bannercreative.BannerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(banner.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BannerCreative{config: bcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bannercreative.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	bcuo.mutation.done = true
	return _node, nil
}
