// Code generated by ent, DO NOT EDIT.

package ent

import (
	"affluo/ent/earninghistory"
	"affluo/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EarningHistoryDelete is the builder for deleting a EarningHistory entity.
type EarningHistoryDelete struct {
	config
	hooks    []Hook
	mutation *EarningHistoryMutation
}

// Where appends a list predicates to the EarningHistoryDelete builder.
func (ehd *EarningHistoryDelete) Where(ps ...predicate.EarningHistory) *EarningHistoryDelete {
	ehd.mutation.Where(ps...)
	return ehd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ehd *EarningHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ehd.sqlExec, ehd.mutation, ehd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ehd *EarningHistoryDelete) ExecX(ctx context.Context) int {
	n, err := ehd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ehd *EarningHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(earninghistory.Table, sqlgraph.NewFieldSpec(earninghistory.FieldID, field.TypeInt64))
	if ps := ehd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ehd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ehd.mutation.done = true
	return affected, err
}

// EarningHistoryDeleteOne is the builder for deleting a single EarningHistory entity.
type EarningHistoryDeleteOne struct {
	ehd *EarningHistoryDelete
}

// Where appends a list predicates to the EarningHistoryDelete builder.
func (ehdo *EarningHistoryDeleteOne) Where(ps ...predicate.EarningHistory) *EarningHistoryDeleteOne {
	ehdo.ehd.mutation.Where(ps...)
	return ehdo
}

// Exec executes the deletion query.
func (ehdo *EarningHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := ehdo.ehd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{earninghistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ehdo *EarningHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := ehdo.Exec(ctx); err != nil {
		panic(err)
	}
}
