// Code generated by ent, DO NOT EDIT.

package ent

import (
	"affluo/ent/gigtracking"
	"affluo/ent/predicate"
	"affluo/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GigTrackingQuery is the builder for querying GigTracking entities.
type GigTrackingQuery struct {
	config
	ctx           *QueryContext
	order         []gigtracking.OrderOption
	inters        []Interceptor
	predicates    []predicate.GigTracking
	withPublisher *UserQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GigTrackingQuery builder.
func (gtq *GigTrackingQuery) Where(ps ...predicate.GigTracking) *GigTrackingQuery {
	gtq.predicates = append(gtq.predicates, ps...)
	return gtq
}

// Limit the number of records to be returned by this query.
func (gtq *GigTrackingQuery) Limit(limit int) *GigTrackingQuery {
	gtq.ctx.Limit = &limit
	return gtq
}

// Offset to start from.
func (gtq *GigTrackingQuery) Offset(offset int) *GigTrackingQuery {
	gtq.ctx.Offset = &offset
	return gtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gtq *GigTrackingQuery) Unique(unique bool) *GigTrackingQuery {
	gtq.ctx.Unique = &unique
	return gtq
}

// Order specifies how the records should be ordered.
func (gtq *GigTrackingQuery) Order(o ...gigtracking.OrderOption) *GigTrackingQuery {
	gtq.order = append(gtq.order, o...)
	return gtq
}

// QueryPublisher chains the current query on the "publisher" edge.
func (gtq *GigTrackingQuery) QueryPublisher() *UserQuery {
	query := (&UserClient{config: gtq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gigtracking.Table, gigtracking.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, gigtracking.PublisherTable, gigtracking.PublisherColumn),
		)
		fromU = sqlgraph.SetNeighbors(gtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GigTracking entity from the query.
// Returns a *NotFoundError when no GigTracking was found.
func (gtq *GigTrackingQuery) First(ctx context.Context) (*GigTracking, error) {
	nodes, err := gtq.Limit(1).All(setContextOp(ctx, gtq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{gigtracking.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gtq *GigTrackingQuery) FirstX(ctx context.Context) *GigTracking {
	node, err := gtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GigTracking ID from the query.
// Returns a *NotFoundError when no GigTracking ID was found.
func (gtq *GigTrackingQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = gtq.Limit(1).IDs(setContextOp(ctx, gtq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{gigtracking.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gtq *GigTrackingQuery) FirstIDX(ctx context.Context) int64 {
	id, err := gtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GigTracking entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GigTracking entity is found.
// Returns a *NotFoundError when no GigTracking entities are found.
func (gtq *GigTrackingQuery) Only(ctx context.Context) (*GigTracking, error) {
	nodes, err := gtq.Limit(2).All(setContextOp(ctx, gtq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{gigtracking.Label}
	default:
		return nil, &NotSingularError{gigtracking.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gtq *GigTrackingQuery) OnlyX(ctx context.Context) *GigTracking {
	node, err := gtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GigTracking ID in the query.
// Returns a *NotSingularError when more than one GigTracking ID is found.
// Returns a *NotFoundError when no entities are found.
func (gtq *GigTrackingQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = gtq.Limit(2).IDs(setContextOp(ctx, gtq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{gigtracking.Label}
	default:
		err = &NotSingularError{gigtracking.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gtq *GigTrackingQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := gtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GigTrackings.
func (gtq *GigTrackingQuery) All(ctx context.Context) ([]*GigTracking, error) {
	ctx = setContextOp(ctx, gtq.ctx, ent.OpQueryAll)
	if err := gtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GigTracking, *GigTrackingQuery]()
	return withInterceptors[[]*GigTracking](ctx, gtq, qr, gtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gtq *GigTrackingQuery) AllX(ctx context.Context) []*GigTracking {
	nodes, err := gtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GigTracking IDs.
func (gtq *GigTrackingQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if gtq.ctx.Unique == nil && gtq.path != nil {
		gtq.Unique(true)
	}
	ctx = setContextOp(ctx, gtq.ctx, ent.OpQueryIDs)
	if err = gtq.Select(gigtracking.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gtq *GigTrackingQuery) IDsX(ctx context.Context) []int64 {
	ids, err := gtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gtq *GigTrackingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gtq.ctx, ent.OpQueryCount)
	if err := gtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gtq, querierCount[*GigTrackingQuery](), gtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gtq *GigTrackingQuery) CountX(ctx context.Context) int {
	count, err := gtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gtq *GigTrackingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gtq.ctx, ent.OpQueryExist)
	switch _, err := gtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gtq *GigTrackingQuery) ExistX(ctx context.Context) bool {
	exist, err := gtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GigTrackingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gtq *GigTrackingQuery) Clone() *GigTrackingQuery {
	if gtq == nil {
		return nil
	}
	return &GigTrackingQuery{
		config:        gtq.config,
		ctx:           gtq.ctx.Clone(),
		order:         append([]gigtracking.OrderOption{}, gtq.order...),
		inters:        append([]Interceptor{}, gtq.inters...),
		predicates:    append([]predicate.GigTracking{}, gtq.predicates...),
		withPublisher: gtq.withPublisher.Clone(),
		// clone intermediate query.
		sql:  gtq.sql.Clone(),
		path: gtq.path,
	}
}

// WithPublisher tells the query-builder to eager-load the nodes that are connected to
// the "publisher" edge. The optional arguments are used to configure the query builder of the edge.
func (gtq *GigTrackingQuery) WithPublisher(opts ...func(*UserQuery)) *GigTrackingQuery {
	query := (&UserClient{config: gtq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gtq.withPublisher = query
	return gtq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Date time.Time `json:"date,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GigTracking.Query().
//		GroupBy(gigtracking.FieldDate).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gtq *GigTrackingQuery) GroupBy(field string, fields ...string) *GigTrackingGroupBy {
	gtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GigTrackingGroupBy{build: gtq}
	grbuild.flds = &gtq.ctx.Fields
	grbuild.label = gigtracking.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Date time.Time `json:"date,omitempty"`
//	}
//
//	client.GigTracking.Query().
//		Select(gigtracking.FieldDate).
//		Scan(ctx, &v)
func (gtq *GigTrackingQuery) Select(fields ...string) *GigTrackingSelect {
	gtq.ctx.Fields = append(gtq.ctx.Fields, fields...)
	sbuild := &GigTrackingSelect{GigTrackingQuery: gtq}
	sbuild.label = gigtracking.Label
	sbuild.flds, sbuild.scan = &gtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GigTrackingSelect configured with the given aggregations.
func (gtq *GigTrackingQuery) Aggregate(fns ...AggregateFunc) *GigTrackingSelect {
	return gtq.Select().Aggregate(fns...)
}

func (gtq *GigTrackingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gtq); err != nil {
				return err
			}
		}
	}
	for _, f := range gtq.ctx.Fields {
		if !gigtracking.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gtq.path != nil {
		prev, err := gtq.path(ctx)
		if err != nil {
			return err
		}
		gtq.sql = prev
	}
	return nil
}

func (gtq *GigTrackingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GigTracking, error) {
	var (
		nodes       = []*GigTracking{}
		withFKs     = gtq.withFKs
		_spec       = gtq.querySpec()
		loadedTypes = [1]bool{
			gtq.withPublisher != nil,
		}
	)
	if gtq.withPublisher != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, gigtracking.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GigTracking).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GigTracking{config: gtq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gtq.withPublisher; query != nil {
		if err := gtq.loadPublisher(ctx, query, nodes, nil,
			func(n *GigTracking, e *User) { n.Edges.Publisher = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gtq *GigTrackingQuery) loadPublisher(ctx context.Context, query *UserQuery, nodes []*GigTracking, init func(*GigTracking), assign func(*GigTracking, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GigTracking)
	for i := range nodes {
		if nodes[i].gig_tracking_publisher == nil {
			continue
		}
		fk := *nodes[i].gig_tracking_publisher
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "gig_tracking_publisher" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (gtq *GigTrackingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gtq.querySpec()
	_spec.Node.Columns = gtq.ctx.Fields
	if len(gtq.ctx.Fields) > 0 {
		_spec.Unique = gtq.ctx.Unique != nil && *gtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, gtq.driver, _spec)
}

func (gtq *GigTrackingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(gigtracking.Table, gigtracking.Columns, sqlgraph.NewFieldSpec(gigtracking.FieldID, field.TypeInt64))
	_spec.From = gtq.sql
	if unique := gtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gtq.path != nil {
		_spec.Unique = true
	}
	if fields := gtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gigtracking.FieldID)
		for i := range fields {
			if fields[i] != gigtracking.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gtq *GigTrackingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gtq.driver.Dialect())
	t1 := builder.Table(gigtracking.Table)
	columns := gtq.ctx.Fields
	if len(columns) == 0 {
		columns = gigtracking.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gtq.sql != nil {
		selector = gtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gtq.ctx.Unique != nil && *gtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range gtq.predicates {
		p(selector)
	}
	for _, p := range gtq.order {
		p(selector)
	}
	if offset := gtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GigTrackingGroupBy is the group-by builder for GigTracking entities.
type GigTrackingGroupBy struct {
	selector
	build *GigTrackingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gtgb *GigTrackingGroupBy) Aggregate(fns ...AggregateFunc) *GigTrackingGroupBy {
	gtgb.fns = append(gtgb.fns, fns...)
	return gtgb
}

// Scan applies the selector query and scans the result into the given value.
func (gtgb *GigTrackingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gtgb.build.ctx, ent.OpQueryGroupBy)
	if err := gtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GigTrackingQuery, *GigTrackingGroupBy](ctx, gtgb.build, gtgb, gtgb.build.inters, v)
}

func (gtgb *GigTrackingGroupBy) sqlScan(ctx context.Context, root *GigTrackingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gtgb.fns))
	for _, fn := range gtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gtgb.flds)+len(gtgb.fns))
		for _, f := range *gtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GigTrackingSelect is the builder for selecting fields of GigTracking entities.
type GigTrackingSelect struct {
	*GigTrackingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gts *GigTrackingSelect) Aggregate(fns ...AggregateFunc) *GigTrackingSelect {
	gts.fns = append(gts.fns, fns...)
	return gts
}

// Scan applies the selector query and scans the result into the given value.
func (gts *GigTrackingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gts.ctx, ent.OpQuerySelect)
	if err := gts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GigTrackingQuery, *GigTrackingSelect](ctx, gts.GigTrackingQuery, gts, gts.inters, v)
}

func (gts *GigTrackingSelect) sqlScan(ctx context.Context, root *GigTrackingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gts.fns))
	for _, fn := range gts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
