// Code generated by ent, DO NOT EDIT.

package commissionplan

import (
	"affluo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldDescription, v))
}

// ClickCommission applies equality check predicate on the "click_commission" field. It's identical to ClickCommissionEQ.
func ClickCommission(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldClickCommission, v))
}

// ImpressionCommission applies equality check predicate on the "impression_commission" field. It's identical to ImpressionCommissionEQ.
func ImpressionCommission(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldImpressionCommission, v))
}

// FirstLeadCommission applies equality check predicate on the "first_lead_commission" field. It's identical to FirstLeadCommissionEQ.
func FirstLeadCommission(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldFirstLeadCommission, v))
}

// RepeatLeadCommission applies equality check predicate on the "repeat_lead_commission" field. It's identical to RepeatLeadCommissionEQ.
func RepeatLeadCommission(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldRepeatLeadCommission, v))
}

// ValidMonths applies equality check predicate on the "valid_months" field. It's identical to ValidMonthsEQ.
func ValidMonths(v int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldValidMonths, v))
}

// MinimumPayout applies equality check predicate on the "minimum_payout" field. It's identical to MinimumPayoutEQ.
func MinimumPayout(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldMinimumPayout, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldIsActive, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldIsDefault, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldContainsFold(FieldDescription, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotIn(FieldType, vs...))
}

// ClickCommissionEQ applies the EQ predicate on the "click_commission" field.
func ClickCommissionEQ(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldClickCommission, v))
}

// ClickCommissionNEQ applies the NEQ predicate on the "click_commission" field.
func ClickCommissionNEQ(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldClickCommission, v))
}

// ClickCommissionIn applies the In predicate on the "click_commission" field.
func ClickCommissionIn(vs ...float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIn(FieldClickCommission, vs...))
}

// ClickCommissionNotIn applies the NotIn predicate on the "click_commission" field.
func ClickCommissionNotIn(vs ...float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotIn(FieldClickCommission, vs...))
}

// ClickCommissionGT applies the GT predicate on the "click_commission" field.
func ClickCommissionGT(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGT(FieldClickCommission, v))
}

// ClickCommissionGTE applies the GTE predicate on the "click_commission" field.
func ClickCommissionGTE(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGTE(FieldClickCommission, v))
}

// ClickCommissionLT applies the LT predicate on the "click_commission" field.
func ClickCommissionLT(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLT(FieldClickCommission, v))
}

// ClickCommissionLTE applies the LTE predicate on the "click_commission" field.
func ClickCommissionLTE(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLTE(FieldClickCommission, v))
}

// ImpressionCommissionEQ applies the EQ predicate on the "impression_commission" field.
func ImpressionCommissionEQ(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldImpressionCommission, v))
}

// ImpressionCommissionNEQ applies the NEQ predicate on the "impression_commission" field.
func ImpressionCommissionNEQ(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldImpressionCommission, v))
}

// ImpressionCommissionIn applies the In predicate on the "impression_commission" field.
func ImpressionCommissionIn(vs ...float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIn(FieldImpressionCommission, vs...))
}

// ImpressionCommissionNotIn applies the NotIn predicate on the "impression_commission" field.
func ImpressionCommissionNotIn(vs ...float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotIn(FieldImpressionCommission, vs...))
}

// ImpressionCommissionGT applies the GT predicate on the "impression_commission" field.
func ImpressionCommissionGT(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGT(FieldImpressionCommission, v))
}

// ImpressionCommissionGTE applies the GTE predicate on the "impression_commission" field.
func ImpressionCommissionGTE(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGTE(FieldImpressionCommission, v))
}

// ImpressionCommissionLT applies the LT predicate on the "impression_commission" field.
func ImpressionCommissionLT(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLT(FieldImpressionCommission, v))
}

// ImpressionCommissionLTE applies the LTE predicate on the "impression_commission" field.
func ImpressionCommissionLTE(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLTE(FieldImpressionCommission, v))
}

// FirstLeadCommissionEQ applies the EQ predicate on the "first_lead_commission" field.
func FirstLeadCommissionEQ(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldFirstLeadCommission, v))
}

// FirstLeadCommissionNEQ applies the NEQ predicate on the "first_lead_commission" field.
func FirstLeadCommissionNEQ(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldFirstLeadCommission, v))
}

// FirstLeadCommissionIn applies the In predicate on the "first_lead_commission" field.
func FirstLeadCommissionIn(vs ...float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIn(FieldFirstLeadCommission, vs...))
}

// FirstLeadCommissionNotIn applies the NotIn predicate on the "first_lead_commission" field.
func FirstLeadCommissionNotIn(vs ...float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotIn(FieldFirstLeadCommission, vs...))
}

// FirstLeadCommissionGT applies the GT predicate on the "first_lead_commission" field.
func FirstLeadCommissionGT(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGT(FieldFirstLeadCommission, v))
}

// FirstLeadCommissionGTE applies the GTE predicate on the "first_lead_commission" field.
func FirstLeadCommissionGTE(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGTE(FieldFirstLeadCommission, v))
}

// FirstLeadCommissionLT applies the LT predicate on the "first_lead_commission" field.
func FirstLeadCommissionLT(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLT(FieldFirstLeadCommission, v))
}

// FirstLeadCommissionLTE applies the LTE predicate on the "first_lead_commission" field.
func FirstLeadCommissionLTE(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLTE(FieldFirstLeadCommission, v))
}

// RepeatLeadCommissionEQ applies the EQ predicate on the "repeat_lead_commission" field.
func RepeatLeadCommissionEQ(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldRepeatLeadCommission, v))
}

// RepeatLeadCommissionNEQ applies the NEQ predicate on the "repeat_lead_commission" field.
func RepeatLeadCommissionNEQ(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldRepeatLeadCommission, v))
}

// RepeatLeadCommissionIn applies the In predicate on the "repeat_lead_commission" field.
func RepeatLeadCommissionIn(vs ...float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIn(FieldRepeatLeadCommission, vs...))
}

// RepeatLeadCommissionNotIn applies the NotIn predicate on the "repeat_lead_commission" field.
func RepeatLeadCommissionNotIn(vs ...float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotIn(FieldRepeatLeadCommission, vs...))
}

// RepeatLeadCommissionGT applies the GT predicate on the "repeat_lead_commission" field.
func RepeatLeadCommissionGT(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGT(FieldRepeatLeadCommission, v))
}

// RepeatLeadCommissionGTE applies the GTE predicate on the "repeat_lead_commission" field.
func RepeatLeadCommissionGTE(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGTE(FieldRepeatLeadCommission, v))
}

// RepeatLeadCommissionLT applies the LT predicate on the "repeat_lead_commission" field.
func RepeatLeadCommissionLT(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLT(FieldRepeatLeadCommission, v))
}

// RepeatLeadCommissionLTE applies the LTE predicate on the "repeat_lead_commission" field.
func RepeatLeadCommissionLTE(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLTE(FieldRepeatLeadCommission, v))
}

// ValidMonthsEQ applies the EQ predicate on the "valid_months" field.
func ValidMonthsEQ(v int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldValidMonths, v))
}

// ValidMonthsNEQ applies the NEQ predicate on the "valid_months" field.
func ValidMonthsNEQ(v int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldValidMonths, v))
}

// ValidMonthsIn applies the In predicate on the "valid_months" field.
func ValidMonthsIn(vs ...int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIn(FieldValidMonths, vs...))
}

// ValidMonthsNotIn applies the NotIn predicate on the "valid_months" field.
func ValidMonthsNotIn(vs ...int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotIn(FieldValidMonths, vs...))
}

// ValidMonthsGT applies the GT predicate on the "valid_months" field.
func ValidMonthsGT(v int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGT(FieldValidMonths, v))
}

// ValidMonthsGTE applies the GTE predicate on the "valid_months" field.
func ValidMonthsGTE(v int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGTE(FieldValidMonths, v))
}

// ValidMonthsLT applies the LT predicate on the "valid_months" field.
func ValidMonthsLT(v int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLT(FieldValidMonths, v))
}

// ValidMonthsLTE applies the LTE predicate on the "valid_months" field.
func ValidMonthsLTE(v int) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLTE(FieldValidMonths, v))
}

// MinimumPayoutEQ applies the EQ predicate on the "minimum_payout" field.
func MinimumPayoutEQ(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldMinimumPayout, v))
}

// MinimumPayoutNEQ applies the NEQ predicate on the "minimum_payout" field.
func MinimumPayoutNEQ(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldMinimumPayout, v))
}

// MinimumPayoutIn applies the In predicate on the "minimum_payout" field.
func MinimumPayoutIn(vs ...float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldIn(FieldMinimumPayout, vs...))
}

// MinimumPayoutNotIn applies the NotIn predicate on the "minimum_payout" field.
func MinimumPayoutNotIn(vs ...float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNotIn(FieldMinimumPayout, vs...))
}

// MinimumPayoutGT applies the GT predicate on the "minimum_payout" field.
func MinimumPayoutGT(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGT(FieldMinimumPayout, v))
}

// MinimumPayoutGTE applies the GTE predicate on the "minimum_payout" field.
func MinimumPayoutGTE(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldGTE(FieldMinimumPayout, v))
}

// MinimumPayoutLT applies the LT predicate on the "minimum_payout" field.
func MinimumPayoutLT(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLT(FieldMinimumPayout, v))
}

// MinimumPayoutLTE applies the LTE predicate on the "minimum_payout" field.
func MinimumPayoutLTE(v float64) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldLTE(FieldMinimumPayout, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldIsActive, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.FieldNEQ(FieldIsDefault, v))
}

// HasPublishers applies the HasEdge predicate on the "publishers" edge.
func HasPublishers() predicate.CommissionPlan {
	return predicate.CommissionPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PublishersTable, PublishersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPublishersWith applies the HasEdge predicate on the "publishers" edge with a given conditions (other predicates).
func HasPublishersWith(preds ...predicate.User) predicate.CommissionPlan {
	return predicate.CommissionPlan(func(s *sql.Selector) {
		step := newPublishersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CommissionPlan) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CommissionPlan) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CommissionPlan) predicate.CommissionPlan {
	return predicate.CommissionPlan(sql.NotPredicates(p))
}
